# Load package
library(rCharts)

# Define UI
shinyUI(
  navbarPage("Jeopardy Win Probability",
             tabPanel("Games",
                      sidebarLayout(
                        # Input Panel
                        sidebarPanel(
                          selectInput("season", label="Season: ", choices=c("Season 1 (1984-1985)",
                                                                            "Season 2 (1985-1986)", "Season 3 (1986-1987)", "Season 4 (1987-1988)",
                                                                            "Season 5 (1988-1989)", "Season 6 (1989-1990)", "Season 7 (1990-1991)",
                                                                            "Season 8 (1991-1992)", "Season 9 (1992-1993)", "Season 10 (1993-1994)",
                                                                            "Season 11 (1994-1995)", "Season 12 (1995-1996)", "Season 13 (1996-1997)",
                                                                            "Season 14 (1997-1998)", "Season 15 (1998-1999)", "Season 16 (1999-2000)",
                                                                            "Season 17 (2000-2001)", "Season 18 (2001-2002)", "Season 19 (2002-2003)",
                                                                            "Season 20 (2003-2004)", "Season 21 (2004-2005)", "Season 22 (2005-2006)",
                                                                            "Season 23 (2006-2007)", "Season 24 (2007-2008)", "Season 25 (2008-2009)",
                                                                            "Season 26 (2009-2010)", "Season 27 (2010-2011)", "Season 28 (2011-2012)",
                                                                            "Season 29 (2012-2013)", "Season 30 (2013-2014)"), selected="Season 30 (2013-2014)"),
                          selectInput("game.description", label="Game: ", choices=c("Jared Hall vs. Angela Murock Hussein vs. James Mardock (2013-09-16)",
                                                                                    "Jared Hall vs. Melissa Jurgens vs. Tova Meyer (2013-09-17)",
                                                                                    "Jared Hall vs. Todd Martin vs. Jen Yoak (2013-09-18)", "Jared Hall vs. Parth Sheth vs. Hillary Kwiatek (2013-09-19)",
                                                                                    "Jared Hall vs. Kellie Chan vs. Matt Volk (2013-09-20)", "Matt Volk vs. Collin Adams vs. Stephanie Femrite Stevens (2013-09-23)",
                                                                                    "Matt Volk vs. Neal Pollack vs. Loni Geerlings (2013-09-24)",
                                                                                    "Neal Pollack vs. Kamal Foreman vs. Eric Winschel (2013-09-25)",
                                                                                    "Neal Pollack vs. Fran Altomare vs. Heidi McEchron (2013-09-26)",
                                                                                    "Neal Pollack vs. Sarah Zucker vs. Andrew Mugica (2013-09-27)",
                                                                                    "Sarah Zucker vs. Fidelito Cortes vs. Meredith Robinson (2013-09-30)",
                                                                                    "Fidelito Cortes vs. Rich Hansen vs. Elisabeth Houlik (2013-10-01)",
                                                                                    "Fidelito Cortes vs. Damian Henri vs. Kathy Johnson (2013-10-02)",
                                                                                    "Damian Henri vs. Rohit Dewan vs. Kristan McMahon (2013-10-03)",
                                                                                    "Damian Henri vs. Cori Wilhelm vs. A. C. Hawley (2013-10-04)",
                                                                                    "Cori Wilhelm vs. Marc Muneal vs. Mary Murrell (2013-10-07)",
                                                                                    "Mary Murrell vs. Erin Hoesly vs. Jason Idalski (2013-10-08)",
                                                                                    "Jason Idalski vs. Theresa Warner vs. Amanda Graves (2013-10-09)",
                                                                                    "Jason Idalski vs. Kate Kwiatkowski vs. William Bernhardt (2013-10-10)",
                                                                                    "William Bernhardt vs. Julie Huffman vs. Greg Buzzard (2013-10-11)",
                                                                                    "Greg Buzzard vs. Loren Gianini vs. Chris Gaiman (2013-10-14)",
                                                                                    "Chris Gaiman vs. Emily Horne vs. Stuart Anderson (2013-10-15)",
                                                                                    "Stuart Anderson vs. Mat Ahn vs. Jane Wanninger (2013-10-16)",
                                                                                    "Stuart Anderson vs. John Emery vs. Korin Kormick (2013-10-17)",
                                                                                    "Stuart Anderson vs. Nolan Martch vs. Samantha Nataro (2013-10-18)",
                                                                                    "Nolan Martch vs. Sharon Warner vs. Bill Tolany (2013-10-21)",
                                                                                    "Bill Tolany vs. Arne Lunde vs. Rose Adams (2013-10-22)", "Bill Tolany vs. Nina Emkin vs. Emily Wood (2013-10-23)",
                                                                                    "Bill Tolany vs. Rebecca Anderson vs. Mike Shapiro (2013-10-24)",
                                                                                    "Mike Shapiro vs. Melanie Hess vs. James Cross (2013-10-25)",
                                                                                    "Mike Shapiro vs. Molly Kossoff vs. Gus Iurillo (2013-10-28)",
                                                                                    "Molly Kossoff vs. Sean Kram vs. Marge Lindblom (2013-10-29)",
                                                                                    "Sean Kram vs. Jennifer Spirko vs. Neal Shah (2013-10-30)", "Jennifer Spirko vs. Rhea Hantelman vs. Jermaine Jones (2013-10-31)",
                                                                                    "Rhea Hantelman vs. Norah McKissic vs. Andrea Massar (2013-11-01)",
                                                                                    "Norah McKissic vs. Ramsin Toma vs. Woody Houchin (2013-11-04)",
                                                                                    "Woody Houchin vs. Rani Peffer vs. Carole Furr (2013-11-05)",
                                                                                    "Rani Peffer vs. Kellie Herson vs. Evan Voorn (2013-11-06)",
                                                                                    "Rani Peffer vs. Adam Johnston vs. Sarah Orman (2013-11-07)",
                                                                                    "Rani Peffer vs. Amanda DeMeola vs. Vimal Murthy (2013-11-08)",
                                                                                    "*Anne Baxter vs. Katie Moriarty vs. Rico Vazquez (2013-11-11)",
                                                                                    "*Patrick Dillon vs. Mary Beth Hammerstrom vs. Kati Sorenson (2013-11-12)",
                                                                                    "*Eli Barrieau vs. James Brown vs. Karen Cafaro (2013-11-13)",
                                                                                    "*Becky Giardina vs. Maryanne Lewell vs. John Pearson (2013-11-14)",
                                                                                    "*Cathy Bloedorn vs. Timothy Shuker-Haines vs. Michael Townes (2013-11-15)",
                                                                                    "*John Pearson vs. Timothy Shuker-Haines vs. Katie Moriarty (2013-11-18)",
                                                                                    "*Patrick Dillon vs. Anne Baxter vs. Becky Giardina (2013-11-19)",
                                                                                    "*Mary Beth Hammerstrom vs. Maryanne Lewell vs. Eli Barrieau (2013-11-20)",
                                                                                    "*Mary Beth Hammerstrom vs. Becky Giardina vs. John Pearson (2013-11-21)",
                                                                                    "*Mary Beth Hammerstrom vs. Becky Giardina vs. John Pearson (2013-11-22)",
                                                                                    "Rani Peffer vs. Johnna Mahoney vs. James Kosmatka (2013-11-25)",
                                                                                    "Rani Peffer vs. Mike Nickel vs. Janel Stogdill (2013-11-26)",
                                                                                    "Mike Nickel vs. Shanna Lafferty vs. John Kyle Grady (2013-11-27)",
                                                                                    "John Kyle Grady vs. Whitney Magendie vs. Steven Durham (2013-11-28)",
                                                                                    "Steven Durham vs. Bryce Johnson vs. Tracy Carlson (2013-11-29)",
                                                                                    "Steven Durham vs. Scott Claremon vs. Maura DeGrande (2013-12-02)",
                                                                                    "Scott Claremon vs. Carlos Ross vs. Tina Nguyen (2013-12-03)",
                                                                                    "Carlos Ross vs. Kaya Blauvelt vs. Brock Thompson (2013-12-04)",
                                                                                    "Carlos Ross vs. Cecilia Cuevas vs. Tahne Aarnes (2013-12-05)",
                                                                                    "Carlos Ross vs. Craig Cornish, Jr. vs. Franke Santos (2013-12-06)",
                                                                                    "Craig Cornish, Jr. vs. Murray Weiss vs. Reem Fattouh (2013-12-09)",
                                                                                    "Craig Cornish, Jr. vs. Phil Lowe vs. Meredith Larson (2013-12-10)",
                                                                                    "Meredith Larson vs. Donna Fairweather-Foley vs. Sam Bernhard (2013-12-11)",
                                                                                    "Meredith Larson vs. Rachel Hirsch vs. Woody Bell (2013-12-12)",
                                                                                    "Woody Bell vs. Tiffany Gholar vs. Evan Struble (2013-12-13)",
                                                                                    "Tiffany Gholar vs. Betsy Foss vs. Matthew Church (2013-12-16)",
                                                                                    "Matthew Church vs. Sandy Howard vs. Debbie Singer (2013-12-17)",
                                                                                    "Matthew Church vs. Curtis Morales vs. Varun Shekhar (2013-12-18)",
                                                                                    "Varun Shekhar vs. Mary Gildea vs. Jenna Johnson (2013-12-19)",
                                                                                    "Varun Shekhar vs. Greg Munda vs. Jon Choi (2013-12-20)", "Jon Choi vs. Kristina Lukach vs. Larry White (2013-12-23)",
                                                                                    "Larry White vs. Bonita Dominguez vs. Missy Flood (2013-12-24)",
                                                                                    "Larry White vs. Anthony Niblett vs. Roxann Smith (2013-12-25)",
                                                                                    "Anthony Niblett vs. Jerry Slowik vs. Genevieve LeClerc (2013-12-26)",
                                                                                    "Jerry Slowik vs. Avram Polinsky vs. Kathy Cacace (2013-12-27)",
                                                                                    "Jerry Slowik vs. Armen Terjimanian vs. Alexis Browsh (2013-12-30)",
                                                                                    "Jerry Slowik vs. Alyson Murray vs. Reggie Austin (2013-12-31)",
                                                                                    "Jerry Slowik vs. Bridget O'Donnell vs. John Coulter (2014-01-01)",
                                                                                    "Jerry Slowik vs. Sarah Olson vs. Rachel Samberg (2014-01-02)",
                                                                                    "Sarah Olson vs. Ilissa Gold vs. Lee May (2014-01-03)", "Sarah Olson vs. Eric Brach vs. Mary Manhardt (2014-01-06)",
                                                                                    "Mary Manhardt vs. Carolyn Gawlik vs. Andrew Nelson (2014-01-07)",
                                                                                    "Andrew Nelson vs. Dinu Nesan vs. Julia Dye (2014-01-08)", "Dinu Nesan vs. Marika Kuspa vs. Seth Tribble (2014-01-09)",
                                                                                    "Seth Tribble vs. Michelle DeGrothy vs. Adrian Ho (2014-01-10)",
                                                                                    "Michelle DeGrothy vs. Miriam Musco vs. Matthew Linnabary (2014-01-13)",
                                                                                    "Michelle DeGrothy vs. Sarah McNitt vs. Osei Boakye (2014-01-14)",
                                                                                    "Sarah McNitt vs. Emily Goodlander vs. Danny Jacobs (2014-01-15)",
                                                                                    "Sarah McNitt vs. Gudrun Juffer vs. Stacy Meyers (2014-01-16)",
                                                                                    "Sarah McNitt vs. Jen Aprahamian vs. Geoff Norcross (2014-01-17)",
                                                                                    "Sarah McNitt vs. Blake Perkins vs. Jon McGuire (2014-01-20)",
                                                                                    "Sarah McNitt vs. Priscilla Emery vs. Emily Gadek (2014-01-21)",
                                                                                    "Priscilla Emery vs. Karen Ruckert vs. Zachary Tomanelli (2014-01-22)",
                                                                                    "Karen Ruckert vs. Jennifer Cross Miller vs. Chip Bell (2014-01-23)",
                                                                                    "Chip Bell vs. Joe Thomas vs. Dana Murray (2014-01-24)", "Chip Bell vs. Julie Singer vs. Bill Hammon (2014-01-27)",
                                                                                    "Julie Singer vs. Arthur Chu vs. Cesar Perez-Gonzalez (2014-01-28)",
                                                                                    "Arthur Chu vs. Erik Post vs. Carolyn Collins (2014-01-29)",
                                                                                    "Arthur Chu vs. Carolyn Collins vs. Maura McKenna (2014-01-30)",
                                                                                    "Arthur Chu vs. Tarn Allen vs. Don Gwinn (2014-01-31)", "*India Cooper vs. Chuck Forrest vs. Jim Scott (2014-02-03)",
                                                                                    "*Leslie Frates vs. Leszek Pawlowicz vs. Andrew Westney (2014-02-04)",
                                                                                    "*Richard Cordray vs. Tom Nosek vs. Leslie Shannon (2014-02-05)",
                                                                                    "*Phoebe Juel vs. Mark Lowenthal vs. Frank Spangenberg (2014-02-06)",
                                                                                    "*Tom Cubbage vs. Jerome Vered vs. Bob Verini (2014-02-07)",
                                                                                    "*James Fulwiler vs. Sarah Stevens vs. Whitney Thompson (2014-02-10)",
                                                                                    "*Laurie Beckoff vs. Ben Juster vs. Cameron Kim (2014-02-11)",
                                                                                    "*Kenesha Bennett vs. Terry O'Shea vs. Kevin Shen (2014-02-12)",
                                                                                    "*Julia Clark vs. Tucker Pope vs. Eric Turner (2014-02-13)",
                                                                                    "*Maria Khrakovsky vs. Erika Sloan vs. Alex Sventeckis (2014-02-14)",
                                                                                    "*Laurie Beckoff vs. Tucker Pope vs. Whitney Thompson (2014-02-17)",
                                                                                    "*Terry O'Shea vs. Ben Juster vs. Eric Turner (2014-02-18)",
                                                                                    "*Kevin Shen vs. Erika Sloan vs. Julia Clark (2014-02-19)", "*Kevin Shen vs. Tucker Pope vs. Terry O'Shea (2014-02-20)",
                                                                                    "*Kevin Shen vs. Tucker Pope vs. Terry O'Shea (2014-02-21)",
                                                                                    "Arthur Chu vs. Sofi Albizuri vs. Josh McIlvain (2014-02-24)",
                                                                                    "Arthur Chu vs. Padraic Connelly vs. Myfanwy Davies (2014-02-25)",
                                                                                    "Arthur Chu vs. Lindsey Stallings vs. Stephen Mellis (2014-02-26)",
                                                                                    "Arthur Chu vs. Chris Sanchez vs. Claire Tuley (2014-02-27)",
                                                                                    "Arthur Chu vs. Semret Lemma vs. Dawn Volmert (2014-02-28)",
                                                                                    "*Rachael Schwartz vs. Babu Srinivasan vs. Eddie Timanus (2014-03-03)",
                                                                                    "*Fritz Holznagel vs. Dan Melia vs. Pam Mueller (2014-03-04)",
                                                                                    "*Robin Carroll vs. Bob Harris vs. Shane Whitlock (2014-03-05)",
                                                                                    "*Dave Abbott vs. Mark Dawson vs. Claudia Perry (2014-03-06)",
                                                                                    "*Jill Bunzendahl Chimka vs. Mike Dupée vs. Brad Rutter (2014-03-07)",
                                                                                    "Arthur Chu vs. Michelle Sheffer vs. Sean Sullivan (2014-03-10)",
                                                                                    "Arthur Chu vs. Kirsten Albair vs. Tony Knechtges (2014-03-11)",
                                                                                    "Arthur Chu vs. Julie Hornick vs. Diana Peloquin (2014-03-12)",
                                                                                    "Diana Peloquin vs. Matt Kish vs. Jessica Rebel (2014-03-13)",
                                                                                    "Matt Kish vs. Thad McCollum vs. Cameron Yahr (2014-03-14)",
                                                                                    "Thad McCollum vs. Jen Cosgrove vs. Gordon Graham (2014-03-17)",
                                                                                    "Gordon Graham vs. Nick Durazo vs. Nora Morrison (2014-03-18)",
                                                                                    "Nick Durazo vs. Gabor Revy vs. Susan Shikany (2014-03-19)",
                                                                                    "Gabor Revy vs. Brendan Getzell vs. Diane Levinson (2014-03-20)",
                                                                                    "Diane Levinson vs. Lindsay Wilson vs. Joe Morse (2014-03-21)",
                                                                                    "Joe Morse vs. Nancy Akerman vs. Derek Arnold (2014-03-24)",
                                                                                    "Nancy Akerman vs. Matt Prasse vs. Nathan Chadwick (2014-03-25)",
                                                                                    "Nancy Akerman vs. Clay Walls vs. Deborah Ellis (2014-03-26)",
                                                                                    "Clay Walls vs. Amy Nienaber vs. Emily Waltenbaugh (2014-03-27)",
                                                                                    "Amy Nienaber vs. Douglas Beeler vs. Julia Levine (2014-03-28)",
                                                                                    "*Colby Burnett vs. Celeste DiNucci vs. Tom Nissley (2014-03-31)",
                                                                                    "*Vijay Balse vs. Roger Craig vs. Stephanie Jass (2014-04-01)",
                                                                                    "*Tom Kavanaugh vs. Larissa Kelly vs. Russ Schumacher (2014-04-02)",
                                                                                    "*Michael Falk vs. Ken Jennings vs. Vinita Kailasanath (2014-04-03)",
                                                                                    "*Dan Pawson vs. Maria Wenglinsky vs. Keith Whitener (2014-04-04)",
                                                                                    "Amy Nienaber vs. Michelle Leppert vs. Jonathan Kuehnle (2014-04-07)",
                                                                                    "Michelle Leppert vs. Annalisa Srivatsan vs. Derrick Shivar (2014-04-08)",
                                                                                    "Derrick Shivar vs. Sandie Baker vs. Ed Hagar (2014-04-09)",
                                                                                    "Sandie Baker vs. Bruce Leaman vs. Jessica Guard (2014-04-10)",
                                                                                    "Sandie Baker vs. Rebecca Baird vs. Monique Aldred (2014-04-11)",
                                                                                    "Sandie Baker vs. Chrissy Swisher vs. Devin Baker (2014-04-14)",
                                                                                    "Sandie Baker vs. Jennie Crabbe vs. J.D. Lape (2014-04-15)",
                                                                                    "Sandie Baker vs. Matt Farr vs. Kathryn Schoenberger (2014-04-16)",
                                                                                    "Sandie Baker vs. Frédérique Delaprée vs. Kristin McAuliffe (2014-04-17)",
                                                                                    "Frédérique Delaprée vs. Jake Bryant vs. E.A. Srere (2014-04-18)",
                                                                                    "Frédérique Delaprée vs. Julia Collins vs. Kris Voss (2014-04-21)",
                                                                                    "Julia Collins vs. Dilip Rajagopalan vs. Donna Innes (2014-04-22)",
                                                                                    "Julia Collins vs. Zia Jones vs. Brad Wright (2014-04-23)", "Julia Collins vs. James Behrens vs. Grace Riley (2014-04-24)",
                                                                                    "Julia Collins vs. Aimee Seligstein vs. Hilary Gaughen (2014-04-25)",
                                                                                    "Julia Collins vs. Bob Kochersberger vs. Sarah Shody (2014-04-28)",
                                                                                    "Julia Collins vs. Mary Twellman vs. Nick Lemek (2014-04-29)",
                                                                                    "Julia Collins vs. Mallory Howe vs. John Ogden (2014-04-30)",
                                                                                    "Julia Collins vs. Marlon Morris vs. Michelle Flaherty (2014-05-01)",
                                                                                    "Julia Collins vs. LaWanda London vs. Elissa Burr (2014-05-02)",
                                                                                    "*Leszek Pawlowicz vs. Robin Carroll vs. Roger Craig (2014-05-05)",
                                                                                    "*Tom Nosek vs. Pam Mueller vs. Russ Schumacher (2014-05-06)",
                                                                                    "*Mark Lowenthal vs. Brad Rutter vs. Dan Pawson (2014-05-07)",
                                                                                    "*Tom Cubbage vs. Rachael Schwartz vs. Ken Jennings (2014-05-08)",
                                                                                    "*Chuck Forrest vs. Mark Dawson vs. Colby Burnett (2014-05-09)",
                                                                                    "*Ken Jennings vs. Russ Schumacher vs. Chuck Forrest (2014-05-12)",
                                                                                    "*Brad Rutter vs. Tom Cubbage vs. Leszek Pawlowicz (2014-05-13)",
                                                                                    "*Roger Craig vs. Pam Mueller vs. Colby Burnett (2014-05-14)",
                                                                                    "*Brad Rutter vs. Ken Jennings vs. Roger Craig (2014-05-15)",
                                                                                    "*Brad Rutter vs. Ken Jennings vs. Roger Craig (2014-05-16)",
                                                                                    "Julia Collins vs. Leah Blumenfeld vs. James Herman (2014-05-19)",
                                                                                    "Julia Collins vs. Kate Hoffman vs. Clayton Walker (2014-05-20)",
                                                                                    "Julia Collins vs. Sirena Terr vs. Lara Brenckle Malmont (2014-05-21)",
                                                                                    "Julia Collins vs. Alex Tran vs. Ryan Real (2014-05-22)", "Julia Collins vs. Steve Buechner vs. Brandon Barnes (2014-05-23)",
                                                                                    "Julia Collins vs. Simone Chavoor vs. Steve Martinez (2014-05-26)",
                                                                                    "Julia Collins vs. Jeanne Kaiser vs. Dylan Gaillard (2014-05-27)",
                                                                                    "Julia Collins vs. Manuel Bermúdez vs. Maggie Davis (2014-05-28)",
                                                                                    "Julia Collins vs. Matt Weldy vs. FeiFei Jiang (2014-05-29)",
                                                                                    "Julia Collins vs. Sami Siegelbaum vs. Wendy Hardenberg (2014-05-30)",
                                                                                    "Julia Collins vs. Debra Walsh vs. Brian Loughnane (2014-06-02)",
                                                                                    "Brian Loughnane vs. Sarah Fremgen vs. Peter Dyakowski (2014-06-03)",
                                                                                    "Sarah Fremgen vs. Heather Powell vs. Guy Wilson (2014-06-04)",
                                                                                    "Sarah Fremgen vs. Stacy Layton vs. Molly Lalonde (2014-06-05)",
                                                                                    "Molly Lalonde vs. Kathy Haas vs. Vince Balzano (2014-06-06)",
                                                                                    "Molly Lalonde vs. Heather Heffner vs. Jack Barry (2014-06-09)",
                                                                                    "Molly Lalonde vs. Cindy Summers vs. Jason Raffile (2014-06-10)",
                                                                                    "Molly Lalonde vs. Darren O'Connor vs. Sari Laufer (2014-06-11)",
                                                                                    "Darren O'Connor vs. Katie Frank vs. Joe Keehnast (2014-06-12)",
                                                                                    "Katie Frank vs. Shelby O'Neill vs. Whitney Marshall (2014-06-13)",
                                                                                    "Katie Frank vs. Andrea West vs. Andrew Winner (2014-06-16)",
                                                                                    "Andrea West vs. Paige Ormiston vs. Peter Solderitsch (2014-06-17)",
                                                                                    "Paige Ormiston vs. Troy Senik vs. Desirée Zicko (2014-06-18)",
                                                                                    "Troy Senik vs. Brian Keele vs. Angie Rasmussen (2014-06-19)",
                                                                                    "Brian Keele vs. Alison Meermans vs. Stacy Gardner (2014-06-20)",
                                                                                    "Alison Meermans vs. James Friscia vs. Michele Consoli (2014-06-23)",
                                                                                    "Alison Meermans vs. Chris Gullo vs. Jennifer Blanton (2014-06-24)",
                                                                                    "Jennifer Blanton vs. Jesse Yu vs. Alana Norton (2014-06-25)",
                                                                                    "Jennifer Blanton vs. Ari Voukydis vs. Patti Youngblood (2014-06-26)",
                                                                                    "Jennifer Blanton vs. Jill Rowley vs. Sunil Hari (2014-06-27)",
                                                                                    "Jill Rowley vs. Melinda Dudley vs. Ben Zimmer (2014-06-30)",
                                                                                    "Jill Rowley vs. Shloka Ananthanarayanan vs. Howard Ray (2014-07-01)",
                                                                                    "Howard Ray vs. Matthew Harney vs. Christi Esterle (2014-07-02)",
                                                                                    "Christi Esterle vs. Jeff Versteeg vs. Beverly Garcia (2014-07-03)",
                                                                                    "Christi Esterle vs. Kay Thanaporn vs. Sally Sheinberg (2014-07-04)",
                                                                                    "Kay Thanaporn vs. Robyn Stone vs. Justin Nigro (2014-07-07)",
                                                                                    "Justin Nigro vs. Maire Kennedy vs. Campbell Warner (2014-07-08)",
                                                                                    "Campbell Warner vs. Sara Tess Neumann vs. Nick Lasik (2014-07-09)",
                                                                                    "Campbell Warner vs. Pete Gittens vs. Jen Fiero (2014-07-10)",
                                                                                    "Jen Fiero vs. Andrew Harris vs. Sandy Carroll (2014-07-11)",
                                                                                    "Jen Fiero vs. Virginia Hatfield vs. Ben-Hur Flores (2014-07-14)",
                                                                                    "Ben-Hur Flores vs. Ed Patterson vs. Anna Lawrence (2014-07-15)",
                                                                                    "Ed Patterson vs. Jerome Azbell vs. Molly Dobbins (2014-07-16)",
                                                                                    "Jerome Azbell vs. Katie Wroblewski vs. Megan Gardner (2014-07-17)",
                                                                                    "Katie Wroblewski vs. Jeff Filippini vs. Winston Nguyen (2014-07-18)",
                                                                                    "*Kat Deabill vs. Cooper Lair vs. Josiah Takang (2014-07-21)",
                                                                                    "*Erin Christopher vs. Selena Groh vs. Jeff Xie (2014-07-22)",
                                                                                    "*Nikki Airi vs. Eileen Bunch vs. William Golden (2014-07-23)",
                                                                                    "*Kevin Huang vs. Alan Koolik vs. Ananya Nrusimha (2014-07-24)",
                                                                                    "*Sam Lerner vs. Sydney Mokel vs. Joe Taglic (2014-07-25)", "*Sydney Mokel vs. Jeff Xie vs. William Golden (2014-07-28)",
                                                                                    "*Joe Taglic vs. Cooper Lair vs. Selena Groh (2014-07-29)", "*Alan Koolik vs. Sam Lerner vs. Kat Deabill (2014-07-30)",
                                                                                    "*Cooper Lair vs. Alan Koolik vs. Jeff Xie (2014-07-31)", "*Cooper Lair vs. Alan Koolik vs. Jeff Xie (2014-08-01)"
                          )),
                          selectInput("var", choices=c("Odds", "Score"), label="Metric"),
                          width=4
                        ),

                        # Show data
                        mainPanel(
                          uiOutput("game_info"),
                          showOutput("viz", lib="morris")
                        ),
                        fluid=F
                      )
             ),

             tabPanel("Test Game State",
                      showOutput("oddsviz", lib="nvd3"),
                      hr(),
                      fluidRow(
                        column(3,
                               numericInput("left.score", label="Left Contestant Score:", value=0),
                               numericInput("center.score", label="Center Contestant Score:", value=0),
                               numericInput("right.score", label="Right Contestant Score:", value=0)),
                        column(3,
                               sliderInput("money.left", label="Money Remaining on Board", min=0, max=54000, value=54000, step=200, format="$#,##0"),
                               selectInput("dd.remaining", label="Daily Doubles Remaining", choices=0:3, selected=3)
                               ),
                        column(3,
                               selectInput("champ.days", label="How many games has the left contestant won before today?", choices=c(0:3, "4+"), selected=0)
                        )
                      ),
                      hr()
             ),

             tabPanel("About",
                      includeMarkdown("about.Rmd"))
  )
)